name: grandchild run
run-name: GrandChild (${{ github.event_name == 'workflow_run' && format('nightly {0}', github.event.workflow_run.created_at) || github.event_name }})

on:
  workflow_run:
    workflows: [child run]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      PUBLISH:
        type: boolean
        description: Publish nightly images and update the 'latest' tag?
        default: false
        required: false

jobs:

  metadata:
    runs-on: ubuntu-22.04
    steps:
      - name: Set build date
        run: env
      - name:
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
