name: great grandchild run
run-name: Great GrandChild (${{ github.event_name == 'workflow_run' && format('nightly {0}', github.event.workflow_run.created_at) || github.event_name }})

on:
  workflow_run:
    workflows:
      - parent run
      - child run
      - grandchild run
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      PUBLISH:
        type: boolean
        description: Publish nightly images and update the 'latest' tag?
        default: false
        required: false

permissions:
  contents: write # to fetch code, and create commits
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  metadata:
    runs-on: ubuntu-22.04
    steps:
      - name: Set build date
        run: env
      - name:
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  waitForWorkflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1

  afterWait:
    name: after-wait
    needs: [waitForWorkflows]
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: run
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: test
        run: echo ${{needs.waitForWorkflows.result}}
      - name: Check needs results
        if: needs.waitForWorkflows.result != 'success'
        run: exit 1
