name: parent run
run-name: Parent (${{ github.event_name == 'workflow_run' && format('nightly {0}', github.event.workflow_run.created_at) || github.event_name }})

on:
  workflow_dispatch:
    inputs:
      PUBLISH:
        type: boolean
        description: Publish nightly images and update the 'latest' tag?
        default: false
        required: false

jobs:
  save_parent:
    runs-on: ubuntu-22.04
    steps:
      - name: Save Parent workflow_id ${{ github.event.workflow_run.id }}
        run: echo ${{ github.event.workflow_run.id }} | tee parent-run-id.txt
      - uses: actions/upload-artifact@v3
        with:
          name: parent-run-id
          path: parent-run-id.txt

  metadata:
    runs-on: ubuntu-22.04
    steps:
      - name: Set build date
        run: env
      - name: Save branch-name
        run: |
          echo nightly-${{ github.run_id }} > ./trial-branch.txt
      - uses: actions/upload-artifact@v3
        with:
          name: trial-branch
          path: trial-branch.txt
