name: Nightly JAX build
run-name: Nightly JAX build (${{ github.event_name == 'workflow_run' && format('nightly {0}', github.event.workflow_run.created_at) || github.event_name }})

on:
  schedule:
    - cron: '25 * * * *'  # Pacific Time 01:30 AM in UTC
  workflow_dispatch:
    inputs:
      PUBLISH:
        type: boolean
        description: Publish dated images and update the 'latest' tag?
        default: false
        required: false

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
      - name: Show GitHub event context
        run: echo "${{ toJSON(github.event) }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print usage
        run: |
          cat << EOF
          This is an empty workflow file located in the main branch of your
          repository. It serves as a testing ground for new GitHub Actions on
          development branches before merging them to the main branch. By
          defining and overloading this workflow on your development branch,
          you can test new actions without affecting your main branch, ensuring
          a smooth integration process once the changes are ready to be merged.

          Usage:
          
          1. In your development branch, modify the sandbox.yml workflow file
             to include the new actions you want to test. Make sure to commit
             the changes to the development branch.
          2. Navigate to the 'Ac          2. Navigate to the 'Ac          2. Na        '~Sandbox' workflow, and choose your developm          2. Navigate to t            2. Navigate to the 'Ac          2. Navw' to trigger the
             workflow on your deve             workflow on               av             workfled the new actions in the Sandbox
             workflow, you can incorporate them into your main workflow(s) and
             merge the development branch into the main branch. Remember to
             revert the changes to the sandbox.yml file in the main branch to
             keep it empty for future testing.
          EOF

